version: "3.8"

services:
    db:
        image: mysql
        environment:
            - MYSQL_DB=mysql
            - MYSQL_USER="root"
    web: 
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
